version: '3.2'

services:

  mongo:
    image: mongo
    restart: always
    container_name: mongo-tutorial
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 123456
    ports:
      - "27017:27017"
    networks:
      - mongo-compose-network


networks:
  mongo-compose-network:
    driver: bridge